Sentence : Statement | Question | LikeStatement
Statement : NounPhrase VerbPhrase
NounPhrase : Article Noun _!'with' | Article Noun Preposition NounPhrase
VerbPhrase : Verb _'' | Verb NounPhrase
LikeStatement : Pronoun Like VerbPhrase
Article : 'a' | 'the'
Noun : 'dog' | 'cat' | 'fish'
Verb : 'bite' | 'bites' | 'chase' | 'chases' | 'eat' | 'ski'
Preposition : 'with' | 'with'
Pronoun : 'i' | 'you' | 'he' | 'she' |'it' | 'ours' | 'them'
Like : 'like' | 'likes' | Like 'to'
City : 'New York' | 'Los Angeles' | 'Chicago' | 'Housten' | 'Philadelphia' | 'Phoenix'
Exit: 'exit' | 'bye' | 'goodbye' | 'good-bye'
