SENTENCE : STATEMENT | QUESTION | EXIT | LIKESTATEMENT
LIKESTATEMENT : PRONOUN LIKE VERB
STATEMENT : NOUNPHRASE VERBPHRASE
NOUNPHRASE : ARTICLE NOUN | ARTICLE NOUN PREPOSITION NOUNPHRASE
VERBPHRASE : VERB | VERB NOUNPHRASE
ARTICLE : "a" | "the"
NOUN : "dog" | "cat" | "fish"
VERB : "bite" | "bites" | "chase" | "chases" | "eat" | "ski"
PREPOSITION : "with"
PRONOUN : "i" | "you" | "he" | "she"
LIKE : "like" | "likes" | LIKE "to"
EXIT: "exit"
